### ISSUE TITLE
missing dependency causes "maximum recursion depth exceeded in comparison" error

### ISSUE THREAD

**Issue by kentbull** [TetraVeda/kaslcred#1]
When a dependency is missing from a schema's dependencies array in the schema map then an infinite recursion exists while trying to pop the missing schema to the end of the list.

Reproduction steps:
1. Use a map JSON with a dependency block that has an invalid schema name, one that doesn't match another `schemaName` property in the other schema entries.

Stack trace:
```
Traceback (most recent call last):
  File "/Users/kbull/.pyenv/versions/3.10.8/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/kbull/.pyenv/versions/3.10.8/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/kbull/.pyenv/versions/3.10.8/lib/python3.10/site-packages/kaslcred/__main__.py", line 16, in <module>
    main(schema_source_dir, schema_results_dir, schema_map_file_path, pretty)
  File "/Users/kbull/.pyenv/versions/3.10.8/lib/python3.10/site-packages/kaslcred/link.py", line 240, in main
    saidified_schemas = link_schemas(schema_source, schemas)
  File "/Users/kbull/.pyenv/versions/3.10.8/lib/python3.10/site-packages/kaslcred/link.py", line 91, in link_schemas
    evaluation_order = calc_eval_order(schemas, evaluation_order=[], popped=[])
  File "/Users/kbull/.pyenv/versions/3.10.8/lib/python3.10/site-packages/kaslcred/link.py", line 72, in calc_eval_order
    return calc_eval_order(schemas, evaluation_order, popped)
  File "/Users/kbull/.pyenv/versions/3.10.8/lib/python3.10/site-packages/kaslcred/link.py", line 72, in calc_eval_order
    return calc_eval_order(schemas, evaluation_order, popped)
  File "/Users/kbull/.pyenv/versions/3.10.8/lib/python3.10/site-packages/kaslcred/link.py", line 72, in calc_eval_order
    return calc_eval_order(schemas, evaluation_order, popped)
  [Previous line repeated 988 more times]
  File "/Users/kbull/.pyenv/versions/3.10.8/lib/python3.10/site-packages/kaslcred/link.py", line 71, in calc_eval_order
    schemas.remove(schemas[popped_index])
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by kentbull** [comment]
Resolved in commit https://github.com/TetraVeda/kaslcred/commit/cc05c53f65de3c87e12247b261f0161b6980680e
